name: Remove File on Pull Request

on:
  pull_request:
    types: [closed]

jobs:
  remove_file:
    runs-on: ubuntu-latest

    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'master'

    steps:
      - name: Set Git user information
        run: |
          git config --global user.name "Git Action"
          git config --global user.email "none@example.com"

      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}

      - name: Fetch the 'develop' branch reference
        run: git fetch origin develop:refs/remotes/origin/master

      - name: Remove the file
        run: |
          git rm .github/workflows/deploy.yml
          git rm .github/workflows/test.yml
          git commit -m "Clear deploy file" --no-verify

      - name: Push changes to the temporary branch
        run: git push origin master
