name: Remove File on Pull Request

on:
  pull_request:
    types: [opened]

jobs:
  remove_file:
    runs-on: ubuntu-latest

    steps:
      - name: Set Git user information
        run: |
          git config --global user.name "Git Action"
          git config --global user.email "none@example.com"

      - name: Check if the base branch is 'master' and the head branch is 'develop'
        run: |
          if [[ "${{ github.event.pull_request.base.ref }}" == "master" && "${{ github.event.pull_request.head.ref }}" == "develop" ]]; then
            echo "Base branch is 'master', and head branch is 'develop'. Proceeding with the workflow..."
          else
            echo "This pull request does not match the specified branches. Skipping the workflow."
            exit 0
          fi

      - name: Checkout the repository
        uses: actions/checkout@v3


      - name: Create a temporary branch for the pull request
        run: |
          git checkout -b temp-branch develop

      - name: Remove the file
        run: |
          git rm .github/workflows/deploy.yml
          git rm .github/workflows/test.yml
          git commit -m "Clear deploy file" --no-verify

      - name: Push changes to the temporary branch
        run: git push origin temp-branch

      - name: Create the pull request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: temp-branch
          title: "Remove file_to_remove.txt"
          body: "This pull request removes file_to_remove.txt from the master branch."
          labels: "automerge"

      - name: Wait for the pull request to be merged
        run: |
          sleep 10 # Wait for 10 seconds to give GitHub time to process the pull request

      - name: Delete the temporary branch
        run: |
          curl -X DELETE -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/git/refs/heads/temp-branch"